### ISSUE TITLE
repo signature issue

### ISSUE THREAD

**Issue by perariontaeadastra** [VirtuBox/nginx-ee#111]
**Attach the following commands output**

- [x] lsb_release -a : 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

- [ ] nginx -V : 

**Describe the bug**
I get this error. 

All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/virtubox:/nginx-ee/xUbuntu_18.04  InRelease: The following signatures were invalid: EXPKEYSIG 188C9FB063F0247A home:virtubox OBS Project <home:virtubox@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/home:/virtubox:/nginx-ee/xUbuntu_18.04/InRelease  The following signatures were invalid: EXPKEYSIG 188C9FB063F0247A home:virtubox OBS Project <home:virtubox@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by frankpanduh** [comment]
Hey, had a similar issue, had to just repull the GPG keys.
Hope this helps! 
`sudo curl -sL https://build.opensuse.org/projects/home:virtubox:nginx-ee/public_key| sudo  apt-key add -`

Best

**Comment by perariontaeadastra** [comment]
> Hey, had a similar issue, had to just repull the GPG keys.
> Hope this helps!
> `sudo curl -sL https://build.opensuse.org/projects/home:virtubox:nginx-ee/public_key| sudo apt-key add -`
> 
> Best

This helped! Thanks a lot!

Regards
