### ISSUE TITLE
module "ngx_http_brotli_filter_module" is already loaded

### ISSUE THREAD

**Issue by Ksdmg** [VirtuBox/nginx-ee#116]
Hello,
I started the script with
`bash <(wget -O - vtb.cx/nginx-ee || curl -sL vtb.cx/nginx-ee) --interactive`

1. (2) Stable
2. (y) Pagespeed
3. (2) Stable Release
4. (1) OpenSSL
5. (1) OpenSSL stable 1.1.1g
6. (n)  NAXSI WAF
7. (y) RTMP streaming module
8. (y) dynamic modules
9. (y) auto-update cronjob

I get the following exception:
```
       Installing Nginx-ee Cronjob            [OK]
       Performing final steps                 [OK]
       Checking nginx configuration           [FAIL]
       Nginx-ee was compiled successfully but there is an error in your nginx configuration

Please look at /tmp/nginx-ee.log or use the command nginx -t to find the issue

Give Nginx-ee a GitHub star : https://github.com/VirtuBox/nginx-ee
root@h2905996:/home/# nginx -t
nginx: [emerg] module "ngx_http_brotli_filter_module" is already loaded in /etc/nginx/modules.conf.d/ngx_http_brotli_filter_module.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
```

I'm running on Ubuntu 18.04.6 LTS with Plesk Obsidian 18.0.39 Update #2

**Comment by TheRealSimonMlr** [comment]
In case this is helpful, 
I can confirm this Bug also happens to me on a clean Plesk install: 
![image](https://user-images.githubusercontent.com/62359912/146545682-f1aac95d-a02d-4edd-887b-048c394a5fc6.png)

Running on Ubuntu 20.04 x86_64 (LTS) with Plesk Obsidian 18.0.40.1

**Comment by Rar9** [comment]
This is a very old bug. Just deleted the files that are mentioned.
