### ISSUE TITLE
run-parts: /etc/cron.daily/nginx-ee exited with return code 1

### ISSUE THREAD

**Issue by Rar9** [VirtuBox/nginx-ee#117]
**Attach the following commands output**

- [ ] Plesk Obsidian 18.0.40.1
- [ ] lsb_release -a :  Ubuntu 18.04.6 LTS
- [ ] nginx -V : 
nginx version: nginx/1.21.4 (VirtuBox Nginx-ee)
built by gcc 9.2.1 20191109 (Ubuntu 9.2.1-19ubuntu1~18.04.york0)
built with OpenSSL 1.1.1  11 Sep 2018
TLS SNI support enabled
configure arguments: --add-module=../naxsi/naxsi_src --with-cc-opt='-m64 -march=native -mtune=native -DTCP_FASTOPEN=23 -g -O3 -fstack-protector-strong -flto -ffat-lto-objects -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wimplicit-fallthrough=0 -fcode-hoisting -Wp,-D_FORTIFY_SOURCE=2 -gsplit-dwarf' --with-ld-opt='-lrt -ljemalloc -Wl,-z,relro -Wl,-z,now -fPIC -flto -ffat-lto-objects' --prefix=/usr/share --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --modules-path=/usr/share/nginx/modules --build='VirtuBox Nginx-ee' --user=nginx --group=nginx --with-file-aio --with-threads --with-http_v2_hpack_enc --with-http_v2_module --with-http_ssl_module --with-pcre-jit --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_gzip_static_module --with-http_gunzip_module --with-http_mp4_module --with-http_sub_module --with-compat --add-module=../ngx_http_substitutions_filter_module --add-dynamic-module=../srcache-nginx-module --add-dynamic-module=../ngx_http_redis --add-dynamic-module=../redis2-nginx-module --add-dynamic-module=../memc-nginx-module --add-module=../ngx_devel_kit --add-module=../set-misc-nginx-module --add-dynamic-module=../ngx_http_auth_pam_module --add-module=../nginx-module-vts --add-dynamic-module=../ipscrubtmp/ipscrub --add-module=../incubator-pagespeed-ngx-latest-stable --add-module=../echo-nginx-module --add-module=../headers-more-nginx-module --add-module=../ngx_cache_purge --add-module=../ngx_brotli --with-zlib=../zlib-cf --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -march=native -ljemalloc' --sbin-path=/usr/sbin/nginx

**Describe the bug**

here the eng of log output
![image](https://user-images.githubusercontent.com/2239608/147917184-973f82ba-69f7-4a15-a4d2-822870e7b828.png)

**Comment by Chathu07** [comment]
I'm getting the same issue (vua email) 


`Cron <root@example> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily ) `
