### ISSUE TITLE
Package 'nginx-custom' and 'nginx-wo' has no installation candidate

### ISSUE THREAD

**Issue by alexeiyakovenko** [VirtuBox/nginx-ee#124]
**Attach the following commands output**

- [ ] lsb_release -a :  20.04
- [ ] nginx -V : 1.21.6

Hello!
I try to change 'nginx-ee' to 'nginx-wo' but its not possible. After `sudo add-apt-repository ppa:wordops/nginx-wo -uy` and `sudo apt install nginx-custom nginx-wo -y` I get error:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package nginx-custom is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  nginx-common

Package nginx-wo is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'nginx-custom' has no installation candidate
E: Package 'nginx-wo' has no installation candidate

```
What can be done?

**Comment by VirtuBox** [comment]
Hello,

you will have to remove the file `/etc/apt/preferences.d/nginx-block` and to unhold nginx package with `sudo apt-mark unhold nginx-wo nginx-common nginx-custom` to install the package from the repository.

**Comment by alexeiyakovenko** [comment]
> Hello,
> 
> you will have to remove the file `/etc/apt/preferences.d/nginx-block` and to unhold nginx package with `sudo apt-mark unhold nginx-wo nginx-common nginx-custom` to install the package from the repository.

Thank you! All good! :)
