### ISSUE TITLE
Applying nginx patches     [FAIL]

### ISSUE THREAD

**Issue by SwarupGolui** [VirtuBox/nginx-ee#141]
##################################
 Compilation summary
##################################

 Detected OS : Ubuntu 20.04.6 LTS
 Detected Arch : x86_64

  - Nginx release : 1.24.0
  - OPENSSL : OpenSSL 1.1.1f
  - Dynamic modules YES
  - Naxsi : NO
  - RTMP : NO

       Installing dependencies                [OK]
       Setting Up Nginx configurations        [OK]
       Installing gcc                         [OK]
       Downloading additionals modules        [OK]
       Downloading zlib                       [OK]
       Downloading brotli                     [OK]
       Downloading nginx                      [OK]
       Applying nginx patches                 [FAIL]

      Please look at /tmp/nginx-ee.log

patching file auto/options
Hunk #1 FAILED at 61.
Hunk #2 FAILED at 236.
Hunk #3 FAILED at 456.
3 out of 3 hunks FAILED -- saving rejects to file auto/options.rej
https://drive.google.com/file/d/1uI3VMT8psujKx-w5wWlQ2TmeVxcMgPZ4/view?usp=share_link    This The log File

**Comment by olegcarguy** [comment]
I'm getting the same issue on Ubuntu 22.04

**Comment by olegcarguy** [comment]
@METALG0D I just tried to install the not stable version of nginx and it worked for me:

##################################
 Compilation summary 
##################################

 Detected OS : Ubuntu 22.04.2 LTS
 Detected Arch : x86_64

  - Nginx release : 1.25.0
  - OPENSSL : OpenSSL 3.0.2 1
  - Dynamic modules YES
  - Naxsi : NO
  - RTMP : NO
  - WordOps : YES

       Installing dependencies                [OK]
       Installing gcc                         [OK]
       Downloading additionals modules        [OK]
       Downloading zlib                       [OK]
       Downloading brotli                     [OK]
       Downloading nginx                      [OK]
       Applying nginx patches                 [OK]
       Configuring nginx build                [OK]
       Compiling nginx                        [OK]
       Updating Nginx manual                  [OK]
       Performing final steps                 [OK]
       Checking nginx configuration           [OK]
       Nginx-ee was compiled successfully !

       Installation log : /tmp/nginx-ee.log

**Comment by METALG0D** [comment]
@olegcarguy How you Install WordOps with this script

**Comment by olegcarguy** [comment]
I install wordops first with the default nginx that comes with wordops.  Then I run this to install the latest nginx and integrate dynamic modules that I need @METALG0D

**Comment by METALG0D** [comment]
problem in this line on nginx-build.sh
curl -sL https://raw.githubusercontent.com/kn007/patch/master/nginx.patch | patch -p1

Change with this line 
curl -sL https://raw.githubusercontent.com/kn007/patch/master/nginx_for_1.23.4.patch | patch -p1

but also dynamic module installation not work...

**Comment by olegcarguy** [comment]
Yes, I can confirm that this workaround works.  Hopefully there will be a permanent fix soon.
