### ISSUE TITLE
Brotli Module causing build error

### ISSUE THREAD

**Issue by nsgoyat** [VirtuBox/nginx-ee#148]
I have tried installing mainline, stable, with dynamic modules/without dynamic modules, but the script is ending well for Ubuntu 20.04 LTS. I can't get NGINX installed successfully.

<img width="313" alt="complition error" src="https://github.com/VirtuBox/nginx-ee/assets/36985369/a5108047-90fe-4965-94ae-6abb703434b0">

Here is the log entry from /tmp/nginx-ee.log

```
adding module in ../ngx_brotli

./configure: error: Brotli library is missing from the ../ngx_brotli/deps/brotli/c directory.

Please make sure that the git submodule has been checked out:

    cd ../ngx_brotli && git submodule update --init && cd /usr/local/src/nginx
```

**Comment by dermodmaster** [comment]
Hey, this pull request should adress this issue.
https://github.com/VirtuBox/nginx-ee/pull/147

You could also try to edit `nginx-build.sh` and replace the line
```git clone --depth=1 https://github.com/google/ngx_brotli /usr/local/src/ngx_brotli -q```
with
```git clone --recursive https://github.com/google/ngx_brotli /usr/local/src/ngx_brotli -q```

OR

add following code, after the first mentioned line
```
            cd /usr/local/src/ngx_brotli
            git submodule update --init
```

**Comment by nsgoyat** [comment]
> Hey, this pull request should adress this issue. #147
> 
> You could also try to edit `nginx-build.sh` and replace the line `git clone --depth=1 https://github.com/google/ngx_brotli /usr/local/src/ngx_brotli -q` with `git clone --recursive https://github.com/google/ngx_brotli /usr/local/src/ngx_brotli -q`
> 
> OR
> 
> add following code, after the first mentioned line `git clone --depth=1 https://github.com/google/ngx_brotli /usr/local/src/ngx_brotli -q`
> 
> ```
>             cd /usr/local/src/ngx_brotli
>             git submodule update --init
> ```

Thank you very much. It worked :)
