### ISSUE TITLE
Nginx 1.25.3 won't compile due to Brotli 

### ISSUE THREAD

**Issue by janiosarmento** [VirtuBox/nginx-ee#151]
When trying to compile Nginx 1.25.3 the script will fail on "Configuring Nginx build". The log will show:

```
adding module in ../ngx_brotli

./configure: error: Brotli library is missing from the ../ngx_brotli/deps/brotli/c directory.

Please make sure that the git submodule has been checked out:

    cd ../ngx_brotli && git submodule update --init && cd /usr/local/src/nginx
```

In order to solve this bug, the git clone command for brotli must include `--recursive`.

**Comment by janiosarmento** [comment]
No need to say, but...

I sent the PR after testing and making sure  `--recursive` would solve the issue (my Nginx is already on 1.25.3 after that).

**Comment by VirtuBox** [comment]
Thanks for your pull request and your contribution @janiosarmento
