### ISSUE TITLE
 the pagespeed only works on the site when I am logged in to wordpress

### ISSUE THREAD

**Issue by kakaroto1500** [VirtuBox/nginx-ee#16]
hello my friend, first of all I want to thank you for the work you are doing
Following your tutorial I was able to activate page speed in wordpress

which left me confused and that when I uncheck the wp
the page speed stops working
in the website

I did exactly as you said in your tutorial.

my ubuntu and 16.04
my nginx is
 nginx -V
nginx version: nginx / 1.15.2

Do you have any tips for helping me?

**Comment by kakaroto1500** [comment]
everything is working now
I had set up my wordpress with redis
so I removed the redis everything ran like magic, now it appeared to me another doubt the redis inside wordpress is not to be a mysql bank cache :(

**Comment by VirtuBox** [comment]
Hello @kakaroto1500, 
I'm not sure to understand. Are you using --wpredis and pagespeed at the same time ?

**Comment by kakaroto1500** [comment]
yes that's right I installed my wordpress using wp-redis

When I removed it, page speed worked fine.

Now I'm confused is not it a good practice to use it with wp-redis?

**Comment by VirtuBox** [comment]
Hello @kakaroto1500, 

--wp-redis stack use redis as full-page cache system for WordPress, with a direct connection between nginx and redis to pass data into redis. So it may cause conflicts between --wpredis and ngx_pagespeed module.

**Comment by kakaroto1500** [comment]
@VirtuBox 
yes I had noticed something strange regarding redis and redis module with pagespeed, even without the redis I am happy with the results of the page speed, if I got something with redis I post as I did :)

Thank you for your attention.
