### ISSUE TITLE
New stable nginx-1.26.0 just released

### ISSUE THREAD

**Issue by jasomdotnet** [VirtuBox/nginx-ee#160]
Hi @VirtuBox, just informing that new stable nginx was just [released](https://nginx.org/en/download.html) on  23 Apr 2024. So maybe came time for HTTP3 in nginx-ee? :)

**Comment by imperpl** [comment]
It is already...

**Comment by jasomdotnet** [comment]
Don't hesitate to finish the sentence...

**Comment by imperpl** [comment]
It is already 100% supported.

**Comment by jasomdotnet** [comment]
Within nginx-ee or what you or within nginx?

**Comment by imperpl** [comment]
nginx-ee

**Comment by jasomdotnet** [comment]
yes, you're right.
