### ISSUE TITLE
Nginx Compile Fail

### ISSUE THREAD

**Issue by wiroy** [VirtuBox/nginx-ee#18]
Hello nginx compile fail error 

Please help me

**Comment by VirtuBox** [comment]
Hello @wiroy,

can you post the content of the file /tmp/nginx-ee.log and give us more informations about your server (the output of the command `lsb_release -a`  will be enough) ?

**Comment by wiroy** [comment]
Okey thank but pagespeed error.

**Comment by VirtuBox** [comment]
Hello, Issue has been fixed
