### ISSUE TITLE
RTMP Error

### ISSUE THREAD

**Issue by wiroy** [VirtuBox/nginx-ee#19]
/usr/local/src/nginx-rtmp-module/ngx_rtmp_eval.c
/usr/local/src/nginx-rtmp-module/ngx_rtmp_eval.c: In function ‘ngx_rtmp_eval’:
/usr/local/src/nginx-rtmp-module/ngx_rtmp_eval.c:160:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 switch (c) {
                 ^~~~~~
/usr/local/src/nginx-rtmp-module/ngx_rtmp_eval.c:170:13: note: here
             case ESCAPE:
             ^~~~
cc1: all warnings being treated as errors
objs/Makefile:2571: recipe for target 'objs/addon/nginx-rtmp-module/ngx_rtmp_eval.o' failed
make[1]: *** [objs/addon/nginx-rtmp-module/ngx_rtmp_eval.o] Error 1
make[1]: Leaving directory '/usr/local/src/nginx'
Makefile:11: recipe for target 'install' failed
make: *** [install] Error 2

Hello RTMP İnstall error. Fix please.

**Comment by VirtuBox** [comment]
Hello @wiroy, 

can you give me the setup used ?
(Nginx mainline or stable ? 
With Pagespeed ? 
With Naxsi ? 
What is your Operating system ?

**Comment by VirtuBox** [comment]
Hello @wiroy,

compilation issue with gcc8.1 has been fixed
