### ISSUE TITLE
Make Fails

### ISSUE THREAD

**Issue by jwogrady** [VirtuBox/nginx-ee#2]
Well, I gave it a shot...  Here is the error.  Thanks for your efforts.

```
cp conf/scgi_params \
	'/etc/nginx/scgi_params.default'
test -f '/etc/nginx/nginx.conf' \
	|| cp conf/nginx.conf '/etc/nginx/nginx.conf'
cp conf/nginx.conf '/etc/nginx/nginx.conf.default'
test -d '/run' \
	|| mkdir -p '/run'
test -d '/var/log/nginx' \
	|| mkdir -p '/var/log/nginx'
test -d '/usr/share/nginx/html' \
	|| cp -R html '/usr/share/nginx'
test -d '/var/log/nginx' \
	|| mkdir -p '/var/log/nginx'
make[1]: Leaving directory '/usr/local/src/nginx'
sudo: unable to resolve host {my host name}
sudo: unable to resolve host {my host name}
```

**Comment by VirtuBox** [comment]
Is the issue resolved with the new release ?

**Comment by dmartuszewski** [comment]
I'm having the same issue
`cp conf/scgi_params \
        '/etc/nginx/scgi_params.default'
test -f '/etc/nginx/nginx.conf' \
        || cp conf/nginx.conf '/etc/nginx/nginx.conf'
cp conf/nginx.conf '/etc/nginx/nginx.conf.default'
test -d '/run' \
        || mkdir -p '/run'
test -d '/var/log/nginx' \
        || mkdir -p '/var/log/nginx'
test -d '/usr/share/nginx/html' \
        || cp -R html '/usr/share/nginx'
test -d '/var/log/nginx' \
        || mkdir -p '/var/log/nginx'
make[1]: Leaving directory '/usr/local/src/nginx'
Failed to execute operation: No such file or directory
Failed to start nginx.service: Unit nginx.service not found.
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] mkdir() "/var/lib/nginx/body" failed (2: No such file or directory)
nginx: configuration file /etc/nginx/nginx.conf test failed
Failed to restart nginx.service: Unit nginx.service not found.
nginx-ee was already set on hold.
nginx-common was already set on hold.`

**Comment by VirtuBox** [comment]
Hello,
Do you use Ubuntu 16.04 LTS or Debian 8 ?
Can you check if there was other error before the compilation ?

**Comment by dmartuszewski** [comment]
Hi
16.04 LTS and no errors before

**Comment by VirtuBox** [comment]
Hello,
can you try with the new script release ?

**Comment by dmartuszewski** [comment]
Works now, thanks.
