### ISSUE TITLE
Config error on ssl_ecdh_curve parameters 

### ISSUE THREAD

**Issue by yyhmsg** [VirtuBox/nginx-ee#21]
Just FYI, on the config changes for TLS 1.2, TLS 1.3
`TLSv1.2 + TLSv1.3
    ##
    # SSL Settings
    ##
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'TLS13+AESGCM+AES128:EECDH+AES128';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;
    ssl_ecdh_curve X25519:sect571r1:secp521r1:secp384r1`

The last line "ecdh_curve" throws an configuration error in nginx (at least when installing stable on ubuntu 16.04) - something about the wrong number of parameters.  The other config set below it on your readme listed for TLS 1.1->1.3 seems to work fine.

**Comment by VirtuBox** [comment]
Hello,
 a **;** was missing at the end of the line. It's now fixed.
