### ISSUE TITLE
Compile fail if one does not choose RMTP

### ISSUE THREAD

**Issue by janiosarmento** [VirtuBox/nginx-ee#22]
Select Mainline with no Pagespeed, no NAXSI, no RMTP and compile will fail at "configure" step.

The only way to compile Nginx is chosing RMTP to be compiled.

**Comment by VirtuBox** [comment]
Issue has been fixed by the pull request https://github.com/VirtuBox/nginx-ee/commit/2202bce5853988bef307613f939bfb6863996ef9.
