### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by anacondaq** [VirtuBox/nginx-ee#25]
### Problem: 
Clean and fresh and updated Ubuntu 18.04
hash: c446c1df359fbb83d5c78097f40d766fac73aa1b

Trying to install it, and it's has issues below:
tl;dr: 

> ./configure: error: C compiler /usr/bin/gcc-8 is not found

**Options selected:**

```
14.2 nginx (stable)
pagespeed (stable) / naxsi
nothing more.
```

Problems:
- can't finish installation.
- selected for some reason 1.15* branch instead of stable 1.14 branch
- gcc not founded for some reason too.

### How reproduce: 
1. vultr / digitalocean / or any other cloud provider with 18.04 ubuntu
2. > bash <(wget -qO - https://raw.githubusercontent.com/VirtuBox/nginx-ee/master/nginx-build.sh)
3. select: sable nginx branch, pagespeed (stable) naxsi, nothing more.
4. you will see the error.

### More Detailed:

```

./configure.  You can see these with 'nginx -V'.
patching file src/event/ngx_event_openssl.c
Hunk #1 succeeded at 1184 (offset 53 lines).
Hunk #2 succeeded at 1723 (offset 53 lines).
Hunk #3 succeeded at 1859 (offset 53 lines).
patching file src/event/ngx_event_openssl.h
Hunk #1 succeeded at 64 (offset 10 lines).
Hunk #2 succeeded at 99 (offset 10 lines).
Hunk #3 succeeded at 112 (offset 10 lines).
patching file src/http/modules/ngx_http_ssl_module.c
Hunk #1 succeeded at 234 (offset 1 line).
Hunk #2 succeeded at 594 (offset 26 lines).
Hunk #3 succeeded at 664 (offset 26 lines).
Hunk #4 succeeded at 858 (offset 26 lines).
patching file src/http/modules/ngx_http_ssl_module.h
checking for OS
Linux 4.15.0-20-generic x86_64
checking for C compiler ... not found

./configure: error: C compiler /usr/bin/gcc-8 is not found


```
   Compilation summary :
       - Nginx release : 1.15.8
       - Pagespeed : Stable
       - Naxsi : YES
       - RTMP : NO
       - EasyEngine : NO
       - Plesk : NO

       Installing dependencies                [OK]
       Downloading additionals modules        [OK]
       Downloading zlib                       [OK]
       Downloading brotli                     [OK]
       Downloading openssl                    [OK]
       Downloading naxsi                      [OK]
       Downloading pagespeed                  [OK]
       Downloading nginx                      [OK]
       Applying nginx patches                 [OK]
        Configuring nginx    [FAIL]           [..]

      Please look at /tmp/nginx-ee.log

root@server:~# nano /tmp/nginx-ee.log

```

**Comment by VirtuBox** [comment]
Hello @anacondaqq,
thanks for your detailled report, I will try to reproduce the issue to understand what is going wrong.

**Comment by anacondaqq** [comment]
If you need any info, just let me know.

**Comment by VirtuBox** [comment]
I have found the error, I will push a fix today

**Comment by VirtuBox** [comment]
> If you need any info, just let me know.

Nginx-ee has been updated and compilation should work properly with Nginx stable release now.
Let me know if the issue is fixed
