### ISSUE TITLE
uwsgi support missing in nginx-ee?

### ISSUE THREAD

**Issue by ByteCollect** [VirtuBox/nginx-ee#28]
Script installed all fine but the nginx.conf check at the end throws out an error.

# nginx -t
nginx: [emerg] unknown directive "uwsgi_param" in /etc/nginx/uwsgi_params:2
nginx: configuration file /etc/nginx/nginx.conf test failed

# /etc/nginx/uwsgi_params
uwsgi_param  QUERY_STRING       $query_string;
uwsgi_param  REQUEST_METHOD     $request_method;
uwsgi_param  CONTENT_TYPE       $content_type;
uwsgi_param  CONTENT_LENGTH     $content_length;

uwsgi_param  REQUEST_URI        $request_uri;
uwsgi_param  PATH_INFO          $document_uri;
uwsgi_param  DOCUMENT_ROOT      $document_root;
uwsgi_param  SERVER_PROTOCOL    $server_protocol;
uwsgi_param  REQUEST_SCHEME     $scheme;
uwsgi_param  HTTPS              $https if_not_empty;

uwsgi_param  REMOTE_ADDR        $remote_addr;
uwsgi_param  REMOTE_PORT        $remote_port;
uwsgi_param  SERVER_PORT        $server_port;
uwsgi_param  SERVER_NAME        $server_name;

# iRedMail v0.9.9 on Ubuntu 18.04.1 LTS

**Comment by VirtuBox** [comment]
Hello @ByteCollect,
uwsgi support was removed in release v3.2. But you can easily override nginx-ee compilation options by using the following command before launching nginx-ee script : 

```bash
export OVERRIDE_NGINX_MODULES="--without-mail_imap_module \
    --without-mail_pop3_module \
    --without-mail_smtp_module \
    --with-http_stub_status_module \
    --with-http_realip_module \
    --with-http_auth_request_module \
    --with-http_addition_module \
    --with-http_geoip_module \
    --with-http_gzip_static_module \
    --with-http_image_filter_module \
    --with-http_mp4_module \
    --with-http_sub_module"
```
It will override the original NGINX_MODULES variable which look like : 

```bash
NGINX_MODULES="--without-http_uwsgi_module \
    --without-mail_imap_module \
    --without-mail_pop3_module \
    --without-mail_smtp_module \
    --with-http_stub_status_module \
    --with-http_realip_module \
    --with-http_auth_request_module \
    --with-http_addition_module \
    --with-http_geoip_module \
    --with-http_gzip_static_module \
    --with-http_image_filter_module \
    --with-http_mp4_module \
    --with-http_sub_module"
```

**Comment by VirtuBox** [comment]
uwsgi support will be back with the release 3.5.0 (will be published today)

**Comment by ByteCollect** [comment]
Hello @VirtuBox 
Thank you for your superb and fast support. I really appreciate it.
Both solutions tested, and both work perfect  :)
THANK YOU!
