### ISSUE TITLE
GeoIP issue

### ISSUE THREAD

**Issue by janiosarmento** [VirtuBox/nginx-ee#3]
When I try using your nginx.conf there is an error due to GeoIP data file:

```
# nginx -t
Error Opening file /usr/share/GeoIP/GeoLitecityv6.dat
nginx: [emerg] GeoIP_open("/usr/share/GeoIP/GeoLitecityv6.dat") failed in /etc/nginx/nginx.conf:38
nginx: configuration file /etc/nginx/nginx.conf test failed
```

I tried downloading the data file from Maxmind, but I was unable to find the correct archive.

As a workaround I commented the two GeoIP directives and everything is fine enough. 👍

**Comment by VirtuBox** [comment]
Yes, I have notice this error and I have added comments before this lines with a quick tutorial about how to use GeoIP module with Nginx 

https://gist.github.com/VirtuBox/9ed03c9bd9169202c358a8be181b7840
