### ISSUE TITLE
Pagespeed module Nginx configuration error. 

### ISSUE THREAD

**Issue by utags** [VirtuBox/nginx-ee#31]
Hello all,

Today I try to install this script support all the nginx additional modules (used the _**--full**_ option). The script shows successfully installed. Then I added "etc/nginx/common/pagespeed-vhost.conf" and "/etc/nginx/conf.d/pagespeed.conf" files (which is mentioned by [you in here](https://github.com/VirtuBox/nginx-ee/tree/master/etc/nginx)). Then I added those conf files to my "sites-available" each configuration files (_inside the server blocks_). After I try to reload nginx it shows an error. When I run nginx -t it shows following entries in those files have issues.

"pagespeed on;"
"pagespeed standby;"

Which means this script not installed pagespeed modules in my VPS? When I run "nginx -v" it doesn't shows pagespeed modules, but it shows other modules.

I have Ubuntu 18.04.1 LTS VPS on Vultr.com. 

> root@user~# nginx -t
> nginx: [emerg] unknown directive "pagespeed" in /etc/nginx/conf.d/pagespeed.conf:2
> nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by VirtuBox** [comment]
Hello @utags,

the issue has been fixed with the commit a7dd93b310cb930b4b21646c6d7b243f8fe05a80.

Regards,

**Comment by utags** [comment]
Dear VirtuBox,

Within next 2 weeks I can't test the new script. Once I test it I'll update. Thanks so much your support and this script.

**Comment by utags** [comment]
Dear VirtuBox,

Is this works with EasyEngine v4?

**Comment by utags** [comment]
I have changed to WordOps. Now no issue at all.

**Comment by VirtuBox** [comment]
Hello @utags,
No, my bash script doesn't work with EasyEngine v4.
But it's fully compatible with EEv3 or WordOps.
