### ISSUE TITLE
OPENSSL error install

### ISSUE THREAD

**Issue by edisoncosta** [VirtuBox/nginx-ee#44]
**Attach the following commands output**

- [x] lsb_release -a : Debian GNU/Linux 9.8 (stretch)
- [x] nginx -V : 1.15.9

**Describe the bug**

**Comment by edisoncosta** [comment]
Detected OS : Debian GNU/Linux 9.8 (stretch)
 Detected Arch : x86_64

  - Nginx release : 1.15.9
  - Dynamic modules NO
  - Pagespeed : NO
  - Naxsi : NO
  - RTMP : NO

       Installing dependencies                [OK]
       Setting Up Nginx configurations        [OK]
       Downloading additionals modules        [OK]
       Downloading zlib                       [OK]
       Downloading brotli                     [OK]
       Downloading openssl      [FAIL]        [..]

      Please look at /tmp/nginx-ee.log


/tmp/nginx-ee.log

### add and commit untracked file ###
[detached HEAD 777e5cff89] pre-checkout
 Committer: root <root@server.clicksophia.com.br>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 19 files changed, 23973 insertions(+), 163 deletions(-)
 create mode 100644 crypto/err/openssl.txt.orig
 create mode 100644 crypto/err/openssl.txt.rej
 create mode 100644 include/openssl/sslerr.h.orig
 create mode 100644 ssl/s3_lib.c.orig
 create mode 100644 ssl/s3_lib.c.rej
 create mode 100644 ssl/ssl_ciph.c.orig
 create mode 100644 ssl/ssl_ciph.c.rej
 create mode 100644 ssl/ssl_lib.c.orig
 create mode 100644 ssl/ssl_locl.h.orig
 create mode 100644 ssl/statem/statem_srvr.c.orig
Fetching origin
### git reset from origin master ###
HEAD is now at 861e45624f Reorganized signature-scheme detection in 'apps/s_cb.c:security_callback_debug' callback-function.
### git checkout commit ###
Previous HEAD position was 861e45624f... Reorganized signature-scheme detection in 'apps/s_cb.c:security_callback_debug' callback-function.
HEAD is now at 4089b43407... Revert "Configure: stop forcing use of DEFINE macros in headers"
From https://github.com/VirtuBox/openssl-patch
 * branch            master     -> FETCH_HEAD
Already up-to-date.
### openssl ciphers patch ###
patching file crypto/err/openssl.txt
Hunk #1 FAILED at 2128.
Hunk #2 FAILED at 2136.
Hunk #3 succeeded at 2798 (offset -67 lines).
Hunk #4 succeeded at 2908 (offset -67 lines).
2 out of 4 hunks FAILED -- saving rejects to file crypto/err/openssl.txt.rej
patching file doc/man1/ciphers.pod
patching file include/openssl/sslerr.h
Hunk #1 succeeded at 597 (offset -4 lines).
Hunk #2 succeeded at 731 (offset -4 lines).
patching file ssl/s3_lib.c
Hunk #1 succeeded at 31 (offset -1 lines).
Hunk #2 succeeded at 129 (offset -1 lines).
Hunk #3 succeeded at 173 (offset -1 lines).
Hunk #4 succeeded at 238 (offset -1 lines).
Hunk #5 succeeded at 302 (offset -1 lines).
Hunk #6 succeeded at 4130 (offset -1 lines).
Hunk #7 succeeded at 4150 (offset -1 lines).
Hunk #8 succeeded at 4194 with fuzz 1 (offset -1 lines).
Hunk #9 succeeded at 4231 (offset -1 lines).
Hunk #10 FAILED at 4263.
1 out of 13 hunks FAILED -- saving rejects to file ssl/s3_lib.c.rej
patching file ssl/ssl_ciph.c
Hunk #1 succeeded at 192 (offset -1 lines).
Hunk #2 succeeded at 297 (offset -1 lines).
Hunk #3 succeeded at 683 (offset -1 lines).
Hunk #4 succeeded at 777 (offset -1 lines).
Hunk #5 FAILED at 787.
Hunk #6 succeeded at 865 (offset -1 lines).
Hunk #7 succeeded at 873 (offset -1 lines).
Hunk #8 succeeded at 885 (offset -1 lines).
Hunk #9 succeeded at 953 (offset -3 lines).
Hunk #10 succeeded at 968 (offset -3 lines).
Hunk #11 succeeded at 979 (offset -3 lines).
Hunk #12 succeeded at 1063 (offset -3 lines).
Hunk #13 succeeded at 1080 (offset -3 lines).
Hunk #14 succeeded at 1259 (offset -3 lines).
Hunk #15 succeeded at 1269 (offset -3 lines).
Hunk #16 succeeded at 1438 (offset -3 lines).
Hunk #17 succeeded at 1451 (offset -3 lines).
Hunk #18 succeeded at 1460 (offset -3 lines).
Hunk #19 succeeded at 1522 (offset -3 lines).
Hunk #20 succeeded at 1540 (offset -3 lines).
Hunk #21 succeeded at 1554 (offset -3 lines).
Hunk #22 succeeded at 1579 (offset -3 lines).
Hunk #23 succeeded at 1595 (offset -3 lines).
Hunk #24 succeeded at 1620 (offset -3 lines).
Hunk #25 succeeded at 1646 with fuzz 2 (offset -3 lines).
Hunk #26 FAILED at 1673.
2 out of 26 hunks FAILED -- saving rejects to file ssl/ssl_ciph.c.rej
patching file ssl/ssl_err.c
patching file ssl/ssl_lib.c
Hunk #1 succeeded at 1119 (offset -1 lines).
Hunk #2 succeeded at 1228 (offset -1 lines).
Hunk #3 succeeded at 2564 (offset -1 lines).
Hunk #4 succeeded at 2640 (offset -1 lines).
Hunk #5 succeeded at 3085 (offset -1 lines).
Hunk #6 succeeded at 3261 (offset -1 lines).
Hunk #7 succeeded at 3939 (offset 1 line).
patching file ssl/ssl_locl.h
Hunk #1 succeeded at 745 (offset 1 line).
Hunk #2 succeeded at 1183 (offset 1 line).
Hunk #3 succeeded at 2312 (offset -3 lines).
Hunk #4 succeeded at 2322 (offset -3 lines).
Hunk #5 succeeded at 2412 (offset -3 lines).
patching file ssl/statem/statem_srvr.c
Hunk #1 succeeded at 1750 (offset -1 lines).
Hunk #2 succeeded at 1931 (offset -3 lines).
Hunk #3 succeeded at 1940 (offset -3 lines).
Hunk #4 succeeded at 2256 (offset -3 lines).

**Comment by VirtuBox** [comment]
Hello @edisoncosta,

issue has been fixed with the PR https://github.com/VirtuBox/nginx-ee/pull/45
