### ISSUE TITLE
OpenSSL_1_1_1c

### ISSUE THREAD

**Issue by vasiler** [VirtuBox/nginx-ee#60]
OpenSSL_1_1_1c released. Is much stable than OpenSSL_1_1_1b?

**Comment by VirtuBox** [comment]
Hello @vasiler, 
I haven't checked the changelog yet, but I'm going to update OpenSSL in the next few days.

**Comment by VirtuBox** [comment]
OpenSSL release bumped to 1.1.1c with PR https://github.com/VirtuBox/nginx-ee/pull/64
