### ISSUE TITLE
ERROR patching file src/event/ngx_event_openssl.c

### ISSUE THREAD

**Issue by Rar9** [VirtuBox/nginx-ee#63]
Ran your script 3 days ago on my ubunu 18.04 and update was easy :-) 

Today plesk changed nginx back to its default version.   (only did plesk installer update) 

Tried to re-run the script but are getting an error  -  applying nginx patch      [FAIL]     

2019-06-25 14:31:42 (5.66 MB/s) - ‘nginx-1.17.0.tar.gz’ saved [1032978/1032978]

--2019-06-25 14:31:42--  https://raw.githubusercontent.com/cujanovic/nginx-dynamic-tls-records-patch/master/nginx__dynamic_tls_records_1.13.0%2B.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8325 (8.1K) [text/plain]
Saving to: ‘nginx__dynamic_tls_records.patch’

     0K ........                                              100% 35.5M=0s

2019-06-25 14:31:42 (35.5 MB/s) - ‘nginx__dynamic_tls_records.patch’ saved [8325/8325]

patching file src/event/ngx_event_openssl.c
Hunk #1 succeeded at 1507 (offset 376 lines).
Hunk #2 succeeded at 2360 (offset 690 lines).
Hunk #3 succeeded at 2502 (offset 696 lines).
patching file src/event/ngx_event_openssl.h
Hunk #1 succeeded at 64 (offset 10 lines).
Hunk #2 FAILED at 89.
Hunk #3 succeeded at 117 (offset 19 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/event/ngx_event_openssl.h.rej
patching file src/http/modules/ngx_http_ssl_module.c
Hunk #1 succeeded at 249 with fuzz 1 (offset 16 lines).
Hunk #2 succeeded at 615 (offset 47 lines).
Hunk #3 succeeded at 687 (offset 49 lines).
Hunk #4 succeeded at 911 with fuzz 1 (offset 79 lines).
patching file src/http/modules/ngx_http_ssl_module.h
Hunk #1 succeeded at 61 (offset 4 lines).

**Comment by VirtuBox** [comment]
Issue has been fixed with PR https://github.com/VirtuBox/nginx-ee/pull/64

**Comment by Rar9** [comment]
Thanks, it works.

Where do i find a working tuned nginx.conf that will work with the compiled version?

**Comment by VirtuBox** [comment]
Hello @Rar9,

I haven't published a tuned nginx.conf for Plesk, mostly because extra configurations are stored in `/etc/nginx/conf.d` with Plesk. But this one would be a good example : [nginx.conf](https://github.com/VirtuBox/ubuntu-nginx-web-server/blob/master/etc/nginx/nginx.conf)

**Comment by Rar9** [comment]
HI,
I tried this but nginx -t gives Error on client_max_body_size 100m;

Next Problem is GeoIP with is believe is now GeoIP2

**Comment by VirtuBox** [comment]
Hello,
From my experience, replacing original nginx.conf isn't a way to proceed with Plesk. 
You can use my nginx.conf as an example, but try to make the lowest amount of change directly in nginx.conf, and prefer creating new .conf file in /etc/nginx/conf.d instead. 
If you have issues with few directives, just comment them. 

I will take a look about GeoIP.
