### ISSUE TITLE
nginx: [emerg] unknown directive "stream" in /etc/nginx/nginx.conf:24

### ISSUE THREAD

**Issue by Firzum** [VirtuBox/nginx-ee#73]
**Attach the following commands output**

- [ ] lsb_release -a : 
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

- [ ] nginx -V : 
nginx -V
nginx version: nginx/1.17.3 (VirtuBox Nginx-ee)
built by gcc 7.4.0 (Ubuntu 7.4.0-9ubuntu1~18.04.york0)
built with OpenSSL 1.1.1c  28 May 2019
TLS SNI support enabled
configure arguments: --add-module=../naxsi/naxsi_src --with-cc-opt='-m64 -march=native -mtune=native -DTCP_FASTOPEN=23 -g -O3 -fstack-protector-strong -flto -ffat-lto-objects -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wimplicit-fallthrough=0 -fcode-hoisting -Wp,-D_FORTIFY_SOURCE=2 -gsplit-dwarf' --with-ld-opt='-lrt -ljemalloc -Wl,-z,relro -Wl,-z,now -fPIC -flto -ffat-lto-objects' --prefix=/usr/share --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --modules-path=/usr/share/nginx/modules --build='VirtuBox Nginx-ee' --with-file-aio --with-threads --with-http_v2_hpack_enc --with-http_v2_module --with-http_ssl_module --with-pcre-jit --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_gzip_static_module --with-http_gunzip_module --with-http_mp4_module --with-http_sub_module --with-compat --add-module=../ngx_http_substitutions_filter_module --add-dynamic-module=../srcache-nginx-module --add-dynamic-module=../ngx_http_redis --add-dynamic-module=../redis2-nginx-module --add-dynamic-module=../memc-nginx-module --add-module=../ngx_devel_kit --add-module=../set-misc-nginx-module --add-dynamic-module=../ngx_http_auth_pam_module --add-module=../nginx-module-vts --add-dynamic-module=../ipscrubtmp/ipscrub --add-module=../incubator-pagespeed-ngx-latest-stable --add-module=../nginx-rtmp-module --add-module=../echo-nginx-module --add-module=../headers-more-nginx-module --add-module=../ngx_cache_purge --add-module=../ngx_brotli --with-zlib=../zlib-cf --with-openssl=../openssl --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -march=native -ljemalloc' --sbin-path=/usr/sbin/nginx

**Describe the bug**
I'm trying to use NGINX as a WAF for other web servers. This NGINX is also doing TCP/UDP load balancing. So I would like to have NAXSI and STREAM load balancing modules enabled.
Is it possible ?

Thanks in advance for your answers.

**Comment by VirtuBox** [comment]
Hello,
yes this is possible, you will just have to overwritte the list of modules compiled by the script as described in the wiki : https://github.com/VirtuBox/nginx-ee/wiki/Nginx-modules

it will look like : 

```bash
export OVERRIDE_NGINX_MODULES="--without-http_uwsgi_module \
    --without-mail_imap_module \
    --without-mail_pop3_module \
    --without-mail_smtp_module \
    --with-http_stub_status_module \
    --with-http_realip_module \
    --with-http_auth_request_module \
    --with-http_addition_module \
    --with-http_geoip_module \
    --with-http_gzip_static_module \
    --with-http_image_filter_module \
    --with-http_mp4_module \
    --with-http_sub_module \
    --with-stream"

bash <(wget -O - vtb.cx/nginx-ee || curl -sL vtb.cx/nginx-ee) --naxsi
```

**Comment by Firzum** [comment]
That's fantastic,n thanks you so much and thanks for this great job !
