### ISSUE TITLE
Reverted to Plesk Nginx?

### ISSUE THREAD

**Issue by XOKP** [VirtuBox/nginx-ee#76]
I installed Nginx-ee on a Plesk server for a few weeks, and then the Nginx and OpenSSL was reverted to older version which I believe the updates from Plesk, is there anything I need to do after I installing Nginx-ee, in order to stop Nginx overwrite from Plesk?

`bash <(wget -O - vtb.cx/nginx-ee || curl -sL vtb.cx/nginx-ee)`

**Comment by VirtuBox** [comment]
Hello @XOKP,
My script cannot prevent Plesk Nginx update because their update script force sw-nginx package upgrade even if the package state is hold or if there is a blocking directive in /etc/apt/preferences.d/.
I haven't found a solution for that yet

**Comment by XOKP** [comment]
Hi @VirtuBox,

Thanks for your confirmation on this. Hope there will be a solution in the near future.
