### ISSUE TITLE
Plesk Obsidian Ready To Market (RTM 18.0.19) 

### ISSUE THREAD

**Issue by Rar9** [VirtuBox/nginx-ee#79]
HI Today I update to new plesk 18.x version.

When i do a 

apt update && apt upgrade && plesk installer update

N: Ignoring file 'plesk.list.ai_back' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: Failed to fetch http://download.opensuse.org/repositories/home:/virtubox:/nginx-ee/xUbuntu_18.04/InRelease  403  Forbidden [IP: 2620:113:80c0:8::13 80]
E: The repository 'http://download.opensuse.org/repositories/home:/virtubox:/nginx-ee/xUbuntu_18.04  InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

what do I need to change?

**Comment by Rar9** [comment]
reinstalling your script seamed to have helped

but now get 

The following packages have been kept back:
  sw-nginx

**Comment by VirtuBox** [comment]
Hello @Rar9,
that mean Plesk installer haven't overwrite nginx-ee with the Nginx package shipped with Plesk.
