### ISSUE TITLE
dev/fd/63: line 157: dpkg-buildflags: command not found

### ISSUE THREAD

**Issue by utags** [VirtuBox/nginx-ee#80]
**Attach the following commands output**

- [ ] OS : Ubuntu 18.04

**Describe the bug**

When I run the virtubox nginx installation it gives me this error. 

dev/fd/63: line 157: dpkg-buildflags: command not found. 

This is the SSH output. 

`root@vultr:~# bash <(wget -O - vtb.cx/nginx-ee || curl -sL vtb.cx/nginx-ee)  --pagespeed

Redirecting output to ‘wget-log’.
/dev/fd/63: line 156: dpkg-buildflags: command not found
/dev/fd/63: line 157: dpkg-buildflags: command not found

Welcome to the nginx-ee bash script v3.6.4

##################################
 Compilation summary
##################################

 Detected OS : Ubuntu 18.04.3 LTS
 Detected Arch : x86_64

  - Nginx release : 1.17.4
  - OPENSSL : 1.1.1c Stable
  - Dynamic modules NO
  - Pagespeed : stable
  - Naxsi : NO
  - RTMP : NO

       Installing dependencies                [OK]
       Setting Up Nginx configurations        [OK]
       Installing gcc-8                       [OK]
       Downloading additionals modules        [OK]
       Downloading zlib                       [OK]
       Downloading brotli                     [OK]
       Downloading pagespeed                  [OK]
       Downloading nginx                      [OK]
       Applying nginx patches                 [OK]
       Configuring nginx                      [OK]
       Compiling nginx                        [..]`

**Comment by VirtuBox** [comment]
Issue has been fixed with PR #82
