### ISSUE TITLE
Stuck at Downloading pagespeed

### ISSUE THREAD

**Issue by 7onmoy** [VirtuBox/nginx-ee#9]
Welcome to the nginx-ee bash script.

Do you want Ngx_Pagespeed ? (y/n)
y

Do you want NAXSI WAF (still experimental)? (y/n)
y
       Installing dependencies                [OK]
       Downloading additionals modules        [OK]
       Downloading brotli                     [OK]
       Downloading openssl                    [OK]
       Downloading naxsi                      [OK]
       Downloading pagespeed               [..]

It's stuck here forever. Upon force stop, it doesn't work anymore unless lock is released. Any idea what's wrong?

**Comment by ashishdungdung** [comment]
Restart your server and try again.

**Comment by VirtuBox** [comment]
@7onmoy Hello, I have tested my bash script again on Debian 8 and Ubuntu 16.04 LTS, and I wasn't able to reproduce this error.

Can you check if curl is installed on your server?
