### ISSUE TITLE
--noconf

### ISSUE THREAD

**Issue by ser** [VirtuBox/nginx-ee#96]
Currently the script forces configuration of nginx. There are use cases when configuration is maintained by ansible or other devops tools. It would be fantastic if an option ```--noconf``` exists where the parts of the script which are responsible for nginx configuration are simply omitted. Just build, install and forget.

I can try to prepare a PR if the idea is accepted.

**Comment by VirtuBox** [comment]
Hello @ser, 
that's an excellent suggestion. Feel free to open a PR and I will merge it. 
Thanks for your contribution.
